GET http://localhost:3000/products

###

GET http://localhost:3000/products/



###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"John",
    "description":"Doe"
}

###

DELETE http://localhost:3000/products/


###

PATCH http://localhost:3000/products/5d69553736a60d330e6a07a7
Content-Type: application/json

{
    "name":"Michael",
}

###

PUT http://localhost:3000/products/
Content-Type: application/json

{
    "name":"James",
    "description":"Smith"
}